version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile-dev
    volumes:
      - .:/usr/src/app
    command: sh -c "npm install && npm run dev"
    ports:
      - '3001:4040'
    extra_hosts:
      - 'host.docker.internal:host-gateway'